### ISSUE TITLE
Have you reproduced Q-CNN result?

### ISSUE THREAD

**Issue by iapcal** [Timo9Madrid7/BEng_Project_Q-CNN#1]
As title, I have tried to reproduce Q-CNN error correction on alexnet with pytorch but failed. I wound to know would it be successful with tensorflow pretrained alexnet model.

Thanks!

**Comment by Timo9Madrid7** [comment]
In my project, I have only done the quantization in the forward propagation, but the error correction happens in the backward pass. I have read some papers relevant to it, and you could have a look. [https://www.cv-foundation.org/openaccess/content_cvpr_2016/papers/Wu_Quantized_Convolutional_Neural_CVPR_2016_paper.pdf] 

I do not know the specific reasons why you failed, but I think using a pre-trained model instead can prove nothing. As I know, the error correction is a process to turn the raw model into the trained one. 

Good luck!

**Comment by iapcal** [comment]
Thanks for your reply and it is very helpful!
I will recheck my code more carefully .
